"""product_has_group tabela

Revision ID: 74f5e1dda120
Revises: a657d8f1727f
Create Date: 2024-08-22 22:27:04.801203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f5e1dda120'
down_revision = 'a657d8f1727f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_has_group',
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_has_group')
    # ### end Alembic commands ###
