"""Commit inicial

Revision ID: ef22e6f9a80a
Revises: 
Create Date: 2024-07-29 03:19:54.157109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef22e6f9a80a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('situation_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('product',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacture_at', sa.String(length=45), nullable=False),
    sa.Column('expiry_at', sa.String(length=45), nullable=False),
    sa.Column('Product_code', sa.String(length=90), nullable=False),
    sa.Column('batch', sa.String(length=60), nullable=False),
    sa.Column('stockQuantity', sa.Double(), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('situation', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['situation'], ['situation_product.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status_product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch'),
    sa.UniqueConstraint('category_id'),
    sa.UniqueConstraint('situation'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('user_id')
    )

    situation_products = [
        {'name': "Longe a data"},
        {'name': "Proximo a data"},
        {'name': "Produto vencido"},
    ]

    status_products = [
        {'name': "Ativo"},
        {'name': "Concluido"},
    ]

    # Adicionando os dados ao banco de dados
    conn = op.get_bind()
    
    # Inserir dados na tabela situation_product
    for situation in situation_products:
        conn.execute(
            sa.text(
                "INSERT INTO situation_product (name) VALUES (:name)"
            ),
            {'name': situation['name']}
        )
    
    # Inserir dados na tabela status_product
    for status in status_products:
        conn.execute(
            sa.text(
                "INSERT INTO status_product (name) VALUES (:name)"
            ),
            {'name': status['name']}
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('user')
    op.drop_table('status_product')
    op.drop_table('situation_product')
    op.drop_table('category')
    # ### end Alembic commands ###
